import { expect, test } from "@playwright/test"
import { addToCart, ana, bruno, card, isMobile, login, logout, password, prepare, setScenario } from "./helpers"

// PNG 1x1 válido para o upload de avatar.
const tinyPng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==", "base64")

test.describe("conta e sessão", () => {
  test("cadastro com validação, conflito, sucesso e logout", async ({ page }, info) => {
    await prepare(page)
    await page.goto("/register")
    const submit = page.getByRole("button", { name: isMobile(info) ? "Criar perfil" : "Criar conta", exact: true })
    await submit.click()
    await expect(page.getByText("Informe o nome de usuário.")).toBeVisible()
    await expect(page.getByText("Informe um e-mail válido.")).toBeVisible()
    await expect(page.getByLabel("E-mail", { exact: true })).toHaveAttribute("aria-invalid", "true")

    await page.getByLabel("Nome de usuário").fill("Nova Coleção")
    await page.getByLabel("E-mail", { exact: true }).fill(ana)
    await page.getByLabel("Senha", { exact: true }).fill(password)
    await page.getByLabel("Confirmar senha", { exact: true }).fill("outra-senha")
    await submit.click()
    await expect(page.getByText("As senhas não conferem.")).toBeVisible()

    await page.getByLabel("Confirmar senha", { exact: true }).fill(password)
    await submit.click()
    await expect(page.getByText("Este e-mail já está em uso.")).toBeVisible()

    await page.getByLabel("E-mail", { exact: true }).fill(`nova.${Date.now()}@kurio.test`)
    await submit.click()
    await expect(page).toHaveURL("/")
    await page.goto("/profile")
    await expect(page.getByLabel("Nome de exibição")).toHaveValue("Nova Coleção")
    await logout(page)
    await page.goto("/profile")
    await expect(page).toHaveURL(/\/login\?redirect=%2Fprofile/)
  })

  test("login, expiração durante a navegação e retorno ao fluxo anterior", async ({ page }, info) => {
    test.skip(isMobile(info), "Menu lateral do perfil validado no desktop")
    await prepare(page)
    await page.goto("/login")
    await page.getByLabel("E-mail", { exact: true }).fill(ana)
    await page.getByLabel("Senha", { exact: true }).fill("errada")
    await page.getByRole("button", { name: "Entrar", exact: true }).click()
    await expect(page.getByRole("alert").filter({ hasText: "E-mail ou senha incorretos." })).toBeVisible()

    await login(page, ana, "/profile")
    await expect(page).toHaveURL("/profile")
    // Espera as consultas da página terminarem antes de invalidar a sessão.
    await expect(page.getByLabel("Nome de exibição")).toHaveValue("Ana Colecionadora")
    await page.waitForLoadState("networkidle")
    await setScenario(page, "session-expired")
    await page.getByRole("navigation", { name: "Meu perfil" }).getByRole("link", { name: "Carteiras" }).click()
    await expect(page).toHaveURL(/\/login\?redirect=%2Fwallets&expired=1/)
    await expect(page.getByText("Sua sessão expirou")).toBeVisible()

    await setScenario(page, "default")
    await page.getByLabel("E-mail", { exact: true }).fill(ana)
    await page.getByLabel("Senha", { exact: true }).fill(password)
    await page.getByRole("button", { name: "Entrar", exact: true }).click()
    await expect(page).toHaveURL("/wallets")
    await page.reload()
    await expect(page.getByRole("heading", { name: "Carteira principal" })).toBeVisible()
  })

  test("logout e troca de usuário isolam favoritos e carrinho", async ({ page }) => {
    await prepare(page)
    await login(page, ana)
    await page.goto("/favorites")
    await expect(card(page, "Emerald Ape #042")).toBeVisible()
    await page.goto("/cart")
    await expect(page.getByRole("link", { name: "Ivory Baron #088" }).first()).toBeAttached()

    await logout(page)
    await login(page, bruno)
    await page.goto("/favorites")
    await expect(card(page, "Golden Signal #160")).toBeVisible()
    await expect(card(page, "Emerald Ape #042")).toHaveCount(0)
    await page.goto("/cart")
    await expect(page.getByText("Seu carrinho está vazio")).toBeVisible()
  })

  test("perfil: validação, conflito da API, avatar e senha persistem", async ({ page }, info) => {
    test.skip(isMobile(info), "Formulário completo validado no desktop")
    await prepare(page)
    await login(page, ana, "/profile")
    const save = page.getByRole("button", { name: "Salvar", exact: true })

    await page.getByLabel("Nome de usuário").fill("AB")
    await save.click()
    await expect(page.getByText("Use de 3 a 24 letras minúsculas", { exact: false })).toBeVisible()
    await expect(page.getByLabel("Nome de usuário")).toBeFocused()

    await page.getByLabel("Nome de usuário").fill("bruno.nomad")
    await save.click()
    await expect(page.getByText("Nome de usuário indisponível.")).toBeVisible()

    await page.getByLabel("Nome de usuário").fill("ana.curadora")
    await page.getByLabel("Nome de exibição").fill("Ana Curadora")
    await page.locator("#pf-avatar").setInputFiles({ name: "avatar.png", mimeType: "image/png", buffer: tinyPng })
    await expect(page.getByRole("img", { name: "Avatar atual" })).toBeVisible()
    await save.click()
    await expect(page.getByRole("status").filter({ hasText: "Perfil atualizado." })).toBeVisible()
    await page.reload()
    await expect(page.getByLabel("Nome de exibição")).toHaveValue("Ana Curadora")
    await expect(page.getByLabel("Nome de usuário")).toHaveValue("ana.curadora")
    await expect(page.getByRole("img", { name: "Avatar atual" })).toBeVisible()

    await page.getByLabel("Senha atual", { exact: true }).fill("errada123")
    await page.getByLabel("Nova senha", { exact: true }).fill("NovaSenha#1")
    await page.getByLabel("Confirmar nova senha", { exact: true }).fill("NovaSenha#2")
    await save.click()
    await expect(page.getByText("As senhas não conferem.")).toBeVisible()
    await page.getByLabel("Confirmar nova senha", { exact: true }).fill("NovaSenha#1")
    await save.click()
    await expect(page.getByText("A senha atual não confere.")).toBeVisible()
    await page.getByLabel("Senha atual", { exact: true }).fill(password)
    await save.click()
    await expect(page.getByRole("status").filter({ hasText: "Perfil e senha atualizados." })).toBeVisible()

    await logout(page)
    await page.goto("/login")
    await page.getByLabel("E-mail", { exact: true }).fill(ana)
    await page.getByLabel("Senha", { exact: true }).fill("NovaSenha#1")
    await page.getByRole("button", { name: "Entrar", exact: true }).click()
    await expect(page).toHaveURL("/")
  })

  test("carteiras: cadastro, validação e edição persistem", async ({ page }, info) => {
    test.skip(isMobile(info), "Formulário completo validado no desktop")
    await prepare(page)
    await login(page, bruno, "/wallets")
    const primary = page.getByRole("form", { name: "Carteira principal" })
    await primary.getByRole("button", { name: "Salvar carteira" }).click()
    await expect(primary.getByText("Informe o nome de exibição.")).toBeVisible()
    await expect(primary.getByText("Informe um endereço 0x", { exact: false })).toBeVisible()

    await primary.getByLabel("Nome de exibição").fill("Bruno Nomad")
    await primary.getByLabel("Apelido da carteira").fill("Cofre")
    await primary.getByLabel("Rede").selectOption("polygon")
    await primary.getByLabel("Nome do perfil").fill("bruno.cofre")
    await primary.getByLabel("Endereço da carteira").click() // campo protegido contra autopreenchimento (readonly até o foco)
    await primary.getByLabel("Endereço da carteira").fill("0x123")
    await primary.getByLabel("Tipo de carteira").selectOption("walletconnect")
    await primary.getByLabel("Código de indicação").click() // campo protegido contra autopreenchimento (readonly até o foco)
    await primary.getByLabel("Código de indicação").fill("KURIO-BRU")
    await primary.getByLabel("Nome ENS").fill("bruno")
    await primary.getByRole("button", { name: "Salvar carteira" }).click()
    await expect(primary.getByText("Informe um endereço 0x", { exact: false })).toBeVisible()

    await primary.getByLabel("Endereço da carteira").click() // campo protegido contra autopreenchimento (readonly até o foco)
    await primary.getByLabel("Endereço da carteira").fill("0xB0B0000000000000000000000000000000000B0B")
    await primary.getByRole("button", { name: "Salvar carteira" }).click()
    await expect(page.getByRole("status").filter({ hasText: "Carteira principal salva." })).toBeVisible()

    await page.reload()
    const saved = page.getByRole("form", { name: "Carteira principal" })
    await expect(saved.getByLabel("Apelido da carteira")).toHaveValue("Cofre")
    await expect(saved.getByLabel("Rede")).toHaveValue("polygon")
    await saved.getByLabel("Apelido da carteira").fill("Cofre frio")
    await saved.getByRole("button", { name: "Salvar carteira" }).click()
    await expect(page.getByRole("status").filter({ hasText: "Carteira principal salva." })).toBeVisible()
    await page.reload()
    await expect(page.getByRole("form", { name: "Carteira principal" }).getByLabel("Apelido da carteira")).toHaveValue("Cofre frio")
  })

  test("sem carteira: cadastrar pelo pagamento e voltar para finalizar", async ({ page }, info) => {
    test.skip(isMobile(info), "Formulário completo validado no desktop")
    await prepare(page)
    await login(page, bruno)
    await addToCart(page, info, "golden-signal-160")
    await page.goto("/checkout")
    await expect(page.getByText("Cadastre uma carteira para pagar")).toBeVisible()
    await page.getByRole("link", { name: "Cadastrar carteira" }).click()
    await expect(page).toHaveURL(/\/wallets\?redirect=%2Fcheckout/)

    const primary = page.getByRole("form", { name: "Carteira principal" })
    await primary.getByLabel("Nome de exibição").fill("Bruno Nomad")
    await primary.getByLabel("Apelido da carteira").fill("Cofre")
    await primary.getByLabel("Rede").selectOption("ethereum")
    await primary.getByLabel("Nome do perfil").fill("bruno.cofre")
    await primary.getByLabel("Endereço da carteira").click() // campo protegido contra autopreenchimento (readonly até o foco)
    await primary.getByLabel("Endereço da carteira").fill("0xB0B0000000000000000000000000000000000B0B")
    await primary.getByLabel("Tipo de carteira").selectOption("metamask")
    await primary.getByLabel("Código de indicação").click() // campo protegido contra autopreenchimento (readonly até o foco)
    await primary.getByLabel("Código de indicação").fill("KURIO-BRU")
    await primary.getByLabel("Nome ENS").fill("bruno")
    await primary.getByRole("button", { name: "Salvar carteira" }).click()

    await expect(page).toHaveURL("/checkout")
    await expect(page.getByRole("button", { name: "Confirmar compra" })).toBeEnabled()
    await expect(page.getByLabel("Endereço da carteira")).toHaveValue("0xB0B0000000000000000000000000000000000B0B")
  })
})
